 name: Generate ASCII Artwork

 on:
    push

 jobs:
    ascii-jobs:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Install Cowsay Program
          uses: sudo apt-get install cowsay -y

        - name: Execute Cowsay CMD
          uses: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

        - name: Test File Exists 
          uses: grep -i "dragon" dragon.txt
          
        - name: Read File
          uses: cat dragon.txt

        - name: List Repo Files
          uses: ls -ltra
