name: Exploring variables and secrets

on: 
  workflow_dispatch: 
 # schedule:
  #  - cron: "*/1 * * * *"


jobs:
 docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        env:
          CONTAINER_REGISTRY: docker.io
          DOCKER_USERNAME: siddharth1
          IMAGE_NAME: github-actions-nginx
        run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

      - name: Docker Login
        env:
          DOCKER_PASSWORD: s3cUrePa5sw0rd
          DOCKER_USERNAME: siddharth1
        run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

      - name: Docker Publish
        env:
          CONTAINER_REGISTRY: docker.io
          DOCKER_USERNAME: siddharth1
          IMAGE_NAME: github-actions-nginx
        run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

 deploy:
  needs: docker
  runs-on: ubuntu-latest
  steps:
     - name: Simulate SSH and Deployment
       run: |
        echo ssh user@your-server-ip
        echo docker login -u siddharth1 -p dummy_password
        echo docker pull docker.io/siddharth1/github-actions-nginx:latest
        echo docker stop nginx-container || true
        echo docker rm nginx-container || true
        echo docker run -d --name nginx-container -p 80:80 docker.io/siddharth1/github-actions-nginx:latest     
